### PR TITLE
Relax upper bounds for semigroups

### PR DESCRIPTION
**Pull request by stevemao**
@tonymorris could you also make a release after this is merged?

### CODE REVIEW

**Comment by tonymorris** [comment]
Thanks! list-zipper-0.0.10

**Comment by stevemao** [comment]
@tonymorris Thanks. I can't find 0.0.10 and there's no such commits. Maybe you haven't pushed?

**Comment by tonymorris** [comment]
Woops, pushed now.

**Comment by stevemao** [comment]
Thank you!

**Pull request merged**
